### ISSUE TITLE
Additional values files missing in argo config yaml

### ISSUE THREAD

**Issue by timroster** [cloud-native-toolkit/terraform-provider-gitops#55]
PRs for argo config yaml are missing `valueFiles:` for helm.

gitops module repo: https://github.com/cloud-native-toolkit/terraform-gitops-cluster-config

Invoked as part of tests using:
```
module "config" {
  source = "github.com/cloud-native-toolkit/terraform-gitops-cluster-config?ref=v1.1.1"

  banner_background_color = "purple"
  banner_text = "ODF Testing"
  banner_text_color = "#fff"
  git_credentials = module.gitops.git_credentials
  gitops_config = module.gitops.gitops_config
  namespace = module.gitops_namespace.name
  server_name = module.gitops.server_name
}
```

committed content in PR:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-ibm-odf-cluster-config
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitops-ibm-odf
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/gitops-ibm-odf/cluster-config
    repoURL: >-
      https://gitea-gitops-ibm-odf.tor-tzaodf-oqj5h6-cluster-2bef1f4b4097001da9502000c44fc2b2-0000.us-east.containers.appdomain.cloud/gitea-admin/gitops-ibm-odf-ocp4
    targetRevision: main
    helm:
      releaseName: cluster-config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
```

correct content should be:

```yaml
...
    helm:
      releaseName: cluster-config
      valueFiles:
      - values.yaml
      - value-default.yaml
```

This was working correctly when https://github.com/cloud-native-toolkit/terraform-gitops-cluster-config/pull/10 was merged.
